name: .NET

on:
  workflow_dispatch:
  schedule:
  - cron: "0 6,7,8,9,10 * * *"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Get Data
      run:  WACovidStats/bin/Debug/net6.0/WACovidStats.exe
    - name: Push Data
      run:  |
          git config user.name ChrisJollyAU
          git config user.email actions@github.com
          git add .
          git commit -m "Update data"
          git push
